version: "3.9"

services:
  postgres:
    image: postgres:16
    env_file: ["./env/.env"]
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4:8
    env_file: ["./env/.env"]
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports: ["5050:80"]
    depends_on: [postgres]

  rabbitmq:
    image: rabbitmq:3-management
    env_file: ["./env/.env"]
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "15672:15672"

  api-gateway:
    build:
      context: ..
      dockerfile: ./apps/api-gateway/Dockerfile
    env_file: ["./env/.env"]
    environment:
      PORT: ${API_GATEWAY_PORT}
      SERVICE_NAME: api-gateway
      # (si la gateway parle à d'autres services via hostname docker)
      RABBITMQ_HOST: ${RABBITMQ_HOST}
    ports: ["${API_GATEWAY_PORT}:3000"]
    depends_on: [rabbitmq]

  auth-service:
    build:
      context: ..
      dockerfile: ./apps/auth-service/Dockerfile
    env_file: ["./env/.env"]
    environment:
      PORT: ${AUTH_PORT}
      SERVICE_NAME: auth-service
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_ACCESS_TTL: ${JWT_ACCESS_TTL}
      JWT_REFRESH_TTL: ${JWT_REFRESH_TTL}
      AUTH_PUBLIC_URL: ${AUTH_PUBLIC_URL}
      EMAIL_VERIFY_SECRET: ${EMAIL_VERIFY_SECRET}
      EMAIL_VERIFY_TTL: ${EMAIL_VERIFY_TTL}
      RABBITMQ_URL: ${RABBITMQ_URL}
      # APP_URL: ${APP_URL}
      # FRONT_URL: ${FRONT_URL}
      # EMAIL_CONFIRM_TTL_MIN: ${EMAIL_CONFIRM_TTL_MIN}
    volumes:
      - ../uploads:/app/uploads
    ports: ["${AUTH_PORT}:3001"]
    depends_on: [postgres]

  products-service:
    build: { context: .., dockerfile: ./apps/products-service/Dockerfile }
    env_file: ["./env/.env"]
    environment:
      PORT: ${PRODUCTS_PORT}
      SERVICE_NAME: products-service
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    ports: ["${PRODUCTS_PORT}:3002"]
    depends_on: [postgres, rabbitmq]

  orders-service:
    build:
      context: ..
      dockerfile: ./apps/orders-service/Dockerfile
    environment:
      PORT: 3003
      SERVICE_NAME: orders-service
    ports: ["3003:3003"]
    depends_on: [postgres, rabbitmq]

  payments-service:
    build:
      context: ..
      dockerfile: ./apps/payments-service/Dockerfile
    environment:
      PORT: 3004
      SERVICE_NAME: payments-service
    ports: ["3004:3004"]
    depends_on: [rabbitmq]

  notifications-service:
    build:
      context: ..
      dockerfile: ./apps/notifications-service/Dockerfile
    env_file: ["./env/.env"]
    environment:
      PORT: ${NOTIFICATIONS_PORT}
      SERVICE_NAME: notifications-service
      RABBITMQ_URL: ${RABBITMQ_URL}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      EMAIL_FROM: ${EMAIL_FROM}
      INCLUDE_PASSWORD_IN_EMAIL: ${INCLUDE_PASSWORD_IN_EMAIL}
    ports: ["${NOTIFICATIONS_PORT}:3005"]
    depends_on: [rabbitmq, mailhog]

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI http://localhost:8025

volumes:
  pgdata:
# version: "3.9"
# services:
#   postgres:
#     image: postgres:16
#     environment:
#       POSTGRES_USER: cvshop
#       POSTGRES_PASSWORD: cvshop
#       POSTGRES_DB: cvshop_dev
#     ports: ["5432:5432"]
#     volumes: ["pgdata:/var/lib/postgresql/data"]
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U cvshop -d cvshop_dev"]
#       interval: 10s
#       timeout: 5s
#       retries: 5
#   pgadmin:
#     image: dpage/pgadmin4:8
#     environment:
#       PGADMIN_DEFAULT_EMAIL: admin@cvshop.com
#       PGADMIN_DEFAULT_PASSWORD: admin
#     ports: ["5050:80"]
#     depends_on: [postgres]

#   rabbitmq:
#     image: rabbitmq:3-management
#     ports:
#       - "5672:5672"
#       - "15672:15672"

#   api-gateway:
#     build:
#       context: ..
#       dockerfile: ./apps/api-gateway/Dockerfile
#     environment:
#       PORT: 3000
#       SERVICE_NAME: api-gateway
#     ports: ["3000:3000"]
#     depends_on: [rabbitmq]

#   auth-service:
#     build:
#       context: ..
#       dockerfile: ./apps/auth-service/Dockerfile
#     environment:
#       PORT: 3001
#       SERVICE_NAME: auth-service
#       DB_HOST: postgres
#       DB_PORT: 5432
#       DB_USER: cvshop
#       DB_PASS: cvshop
#       DB_NAME: cvshop_dev
#       JWT_ACCESS_SECRET: super_access_secret_dev
#       JWT_REFRESH_SECRET: super_refresh_secret_dev
#       JWT_ACCESS_TTL: 15m
#       JWT_REFRESH_TTL: 7d
#     ports: ["3001:3001"]
#     depends_on: [postgres, rabbitmq]

#   products-service:
#     build:
#       context: ..
#       dockerfile: ./apps/products-service/Dockerfile
#     environment:
#       PORT: 3002
#       SERVICE_NAME: products-service
#     ports: ["3002:3002"]
#     depends_on: [postgres, rabbitmq]

#   orders-service:
#     build:
#       context: ..
#       dockerfile: ./apps/orders-service/Dockerfile
#     environment:
#       PORT: 3003
#       SERVICE_NAME: orders-service
#     ports: ["3003:3003"]
#     depends_on: [postgres, rabbitmq]

#   payments-service:
#     build:
#       context: ..
#       dockerfile: ./apps/payments-service/Dockerfile
#     environment:
#       PORT: 3004
#       SERVICE_NAME: payments-service
#     ports: ["3004:3004"]
#     depends_on: [rabbitmq]

#   notifications-service:
#     build:
#       context: ..
#       dockerfile: ./apps/notifications-service/Dockerfile
#     environment:
#       PORT: 3005
#       SERVICE_NAME: notifications-service
#     ports: ["3005:3005"]
#     depends_on: [rabbitmq]

# volumes:
#   pgdata:
