classpath=.
url=jdbc:postgresql://localhost:5432/cvshop_dev
username=cvshop
password=cvshop
changeLogFile=database/products/changelog-master.xml
defaultSchemaName=public
# liquibase.hub.mode=off

# classpath=.
# # Utilise le nom du service docker 'postgres' (et pas localhost)
# url=jdbc:postgresql://postgres:5432/cvshop_dev
# username=cvshop
# password=cvshop

# # Chemin relatif OK car tu lances Liquibase depuis /workspace (cf. working_dir)
# changeLogFile=database/products/changelog-master.xml

# defaultSchemaName=public
# liquibase.hub.mode=off
